<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="2" skipped="0" tests="2" time="0.101" timestamp="2024-09-03T16:01:23.684245" hostname="uri"><testcase classname="test_operations" name="test_func" time="0.001"><failure message="assert 7 == 6&#10; +  where 6 = func(4, 2)">def test_func():
&gt;       assert 7 == func(4, 2)
E       assert 7 == 6
E        +  where 6 = func(4, 2)

test_operations.py:5: AssertionError</failure></testcase><testcase classname="test_sample" name="test_answer" time="0.001"><failure message="assert 4 == 5&#10; +  where 4 = func(3)">def test_answer():
&gt;       assert func(3) == 5
E       assert 4 == 5
E        +  where 4 = func(3)

test_sample.py:6: AssertionError</failure></testcase></testsuite></testsuites>